/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iris_eyeiris_MainActivity */

#ifndef _Included_com_iris_eyeiris_MainActivity
#define _Included_com_iris_eyeiris_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iris_eyeiris_MainActivity
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iris_eyeiris_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
