/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iris_eyeiris_ApplicationTest */

#ifndef _Included_com_iris_eyeiris_ApplicationTest
#define _Included_com_iris_eyeiris_ApplicationTest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
