//
// Created by ywj on 15/10/8.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iris_eyeiris_ApplicationTest */

#ifndef _Included_com_iris_eyeiris_MainActivity
#define _Included_com_iris_eyeiris_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iris_eyeiris_ApplicationTest
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iris_eyeiris_MainActivity_sayHi
        (JNIEnv *env, jobject obj) {
    return (*env).NewStringUTF("NDK 测试成功");
}

#ifdef __cplusplus
}
#endif
#endif
